---
- hosts: control
  tasks:
   - name: install tools
     apt: name={{item}} state=present update_cache=true
     become: true
     with_items:
      - curl
      - tree
   - name: "add Python 2.7 repo"
     command: "add-apt-repository ppa:fkrull/deadsnakes-python2.7"
     become: true
   - name: Update apt repo index
     apt:
      update_cache: yes
     become: true
   - name: Upgrade Python package to the latest version
     apt:
      name: "python"
      state: latest
     become: true
