---
- hosts: loadbalancer
  become: true
  tasks: 
   - name: verify nginx service
     command: service nginx status
   - name: check nginx port
     wait_for: port=80 timeout=1
- hosts: webserver
  become: true
  tasks:
   - name: verify apache2 status
     command: service apache2 status
   - name: check apache2 port
     wait_for: port=80 timeout=1
- hosts: database
  become: true
  tasks:
   - name: verify mysql status
     command: service mysql status
   - name: check apache2 port
     wait_for: port=3306 timeout=1
